### ISSUE TITLE
Seems to stop alerts going to the Texecom app?

### ISSUE THREAD

**Issue by paulhollands** [dchesterton/texecom2mqtt-hassio#47]
The integration works great and its so useful to have access to all the alarm sensors within HA, but I've noticed that I no longer receive state change alerts from the Texecom app on my phone. Is this normal? 

I run the Texecom2mqtt app within docker and when I stop the container, all the messages will then flood through to the Texecom app.

I'm less concerned about the alarm state changes since HA deals/alerts those, but would like the reassurance that when the alarm is triggered the Texecom app still receives the alert since it can generate a sound overriding the silent setting of the phone which the app is installed.

**Application version**
Latest image

**Texecom alarm type**
Premier Elite 88

**Debug log**
No errors generated. Its working fine

**Comment by asantaga** [comment]
Hey, This is alas by design :-( , see the readme.md at the bottom. 

Because each com port can only be associated with one concurrent app, its either texecom cloud+app or Home Assistant. 
Workarounds 
- Install a 3rd Com unit, like a comIP or a com wifi? , bind two connections to texecom cloud and the 3rd one to this integration
- Use a different approach

Ive decided to use a different approach and am reusing something i built for my old guardsec. I built a pcb which uses esp8266 to monitor the two programable ports, so I can detect if the alarm is set, or part set. You can also use the digital ports (need esp32) and get more info.   Alas this approach is MUCH more limited, all i get is the basic alarm set/no set etc, but that works for me.

I might add a com port to get the full monty in the future

**Comment by paulhollands** [comment]
Thanks. Clearly I should have read the readme fully :)

I think I'll go for an additional com unit

**Comment by ep1cman** [comment]
I was wondering if someone could explain how to add a third com port? All the units I've seen seem to only have 2.

**Comment by LindsayReid** [comment]
If you get an answer please ;let me know - I never managed to get both the
texecopm2mqtt and the Texecom app working at the same time.

Could not get a third com port working despite having bought the extra
interface. Could not work out how to configure Wintek up (or the panel) to
define the port
and baud rate. Gave up with the Texecom mobile app as Texecom2mqtt has
proved far more useful and lets me use all the Texecom sensors for both the
Texecom
alarm system and home assistant.

**Comment by ep1cman** [comment]
What panel are you using? The ones I looked at only have 2 com ports.

**Comment by paulhollands** [comment]
I have an Elite 88 panel and added a 3rd port which is part number CEJ-0001 "Texecom Premier Elite ComIP IP Communicator"

**Comment by ep1cman** [comment]
Where do you connect the 3rd com port? The instruction manual only mentions 2 for the 88:
![814FC497-C41D-4C53-A573-B7D0F87D0477](https://user-images.githubusercontent.com/5303409/173452969-9da9fe09-8dfd-4a0f-b694-d8a3a3dc5994.jpeg)

**Comment by paulhollands** [comment]
CEJ-0001 should come with an expansion adapter which plugs into port 13. This gives you the additional Comport.
![Screenshot_20220614-065633_Gallery](https://user-images.githubusercontent.com/98087603/173504153-8e345b36-8ae6-4bd9-8537-8172d6c7b231.jpg)

**Comment by MikeLDPT** [comment]
> The integration works great and its so useful to have access to all the alarm sensors within HA, but I've noticed that I no longer receive state change alerts from the Texecom app on my phone. Is this normal?
> 
> I run the Texecom2mqtt app within docker and when I stop the container, all the messages will then flood through to the Texecom app.

Hi.  I also experienced this some time ago, and have been thinking about it on and off since.  The COMIP solution seems very expensive for the pleasure of getting "state change **alerts**" to the texecom app on the phone. By the way we have the app installed on two phones, and both phone apps still seem to get state updates of all sensors fine in near realtime when the HA Texecom2MQTT is running, and it is _just_ the State change **alerts** that are missing as you wrote.

As you also mentioned, when you stop Texecom2MQTT the state change alerts thus far not received on the texecom apps come flooding in. If this happens after many weeks it can be quite annoying having so many old alerts beeping away!

My Texecom is under the control of an alarm company and so I have a bit less flexibility and possibly rather more cost associated with any modifcations. 

Anyway, I was wondering if it was possible to have a work around whereby a change the Texecom2MQTT code would perform a temporary disconnect from the ELITE panel after a **final** state alert arrives at TEXECOM2MQTT (an example of a final state alert being "set" rather than "setting" so that the alert(s) also travels to the texecom app during the break? Perhaps the length of the disconnect could be configurable for a specified number of seconds to cater for variations with different user set up.  What do you think?

I expect we'll need Daniel Chesterton (@dchesterton) to review this as a viable option and provide expertise in implementing it if it is viable.  Unfortunately I can't see any evidence that Daniel has had any spare time to concentrate on his much appreciated HA endeavours recently though(?)
