### ISSUE TITLE
Texecom2mqtt not publishing to the homeassistant topic

### ISSUE THREAD

**Issue by lodesmets** [dchesterton/texecom2mqtt-hassio#88]
Edit 15/10/2023:
For anyone having the same problem, just downgrade the mqtt server back to version 1.6.X

**Describe the bug**
When starting, the program doesn't publish to the homeassistant topic, but in the debug logs, i see:
2023-09-28T18:19:11.148882406Z 2023-09-28 18:19:11 - DEBUG: Publishing to homeassistant/alarm_control_panel/texecom2mqtt/................ (extra info omitted for privacy)

But both home assistant, and MQTT explorer don't see that message

But the other topics, it publishes just fine.

I put this in the config file:
homeassistant:
    discovery: true # Optional: enable Home Assistant discovery (default: false)
    prefix: homeassistant # Optional: Home Assistant MQTT topic prefix (default: homeassistant)

**Application version**
V1.2.3

**Texecom alarm type**
Premier Elite 88

**Debug log**
2023-09-28T18:19:11.148882406Z 2023-09-28 18:19:11 - DEBUG: Publishing to homeassistant/alarm_control_panel/texecom2mqtt/................ (extra info omitted for privacy)

**Comment by ali2992** [comment]
I am also seeing this issue, same observations, logs indicate message is being published but no message is received on the broker. The client is connected successfully and can be verified in the broker logs.

**Comment by LindsayReid** [comment]
I have had a couple of recent events when a Texecom event was detected (a PIR according to the Texeom2mqtt log) which was a trigger for a Home Assistant automation event - the trace log for the automation does not show the trigger having been received. 

I had put previous occasional "inactions" down to a  WiFi/Zigbee message not being received but now, looking at the automation trace log, the automation was never triggered. Perhaps I too am suffering from the same problem as described above. More investigation is needed - it's shame that Daniel has not been seen here to help is for some time.  He is the only one who has the original source code due to the constraints of the NDA he had to sign to get the API access.

**Comment by lodesmets** [comment]
The weird thing is that other messages come through just fine

Maybe I should message @dchesterton, because I have the NDA through my company, and see if he is willing to share the code

**Comment by ptruman** [comment]
I'll add that I just updated my MQTT broker (Mosquitto) and now I've got the same issue - the alarm shows in HASS but all sensors are AWOL

**Comment by lodesmets** [comment]
> I'll add that I just updated my MQTT broker (Mosquitto) and now I've got the same issue - the alarm shows in HASS but all sensors are AWOL

What version were you using?


Do you use password. Or is your mqtt server open?

**Comment by ptruman** [comment]
I upgraded to "latest" - but went back to 2.0.17
Open server (no-auth config) at the mo - but I have trashed docker MQTT, reinstalled 2.0.17 and all fine - then back to latest.

**Comment by lodesmets** [comment]
So the funny thing is I already encountered (and "solved") the problem in the past with a different project.

In the past I made an ESP32 module that sends mqtt messages, and suddenly it also stopped working.
Back then I downgraded my mqtt server back to version 1.6.X. This fixes the problem, but @dchesterton should probably just update the mqtt library

**Comment by ali2992** [comment]
What’s the best way to downgrade MQTT server? Seems mad that so many are reliant on an add on that is effectively closed source and maintained by one person.

**Comment by ptruman** [comment]
Use a Docker image and pick the right label.  If you use :latest it will
eventually get updated.

As said, I got mine back to latest ok after I reset my dchesteron image, as
I think something got screwed up in there.

**Comment by dchesterton** [comment]
Author here 👋 I believe the issue was introduced in Mosquitto v2.0.16, specifically this issue: https://github.com/eclipse/mosquitto/issues/2876. I saw similar issues when it first came out but they were fixed in v2.0.17.

So if you upgrade to the latest version of the Mosquitto broker (v2.0.18), it should fix the problem. If you are stuck on v2.0.16 for any particular reason, I believe changing the QoS from 2 to 1 or 0 in your config should also fix the problem.

> Seems mad that so many are reliant on an add on that is effectively closed source and maintained by one person.

I wish I could open source it fully but I've signed an NDA with Texecom who won't allow it.

> This fixes the problem, but @dchesterton should probably just update the mqtt library

The bug is with the MQTT broker. Which broker you use is out of my control so you'll need to update it.

**Comment by LindsayReid** [comment]
Well at least it is good to know that Daniel is still around to look at things. I would feel much more secure if there was at least one other person who had signed the NDA with Texecom and had access to the source. That is not the same as "open source" and some others here have mentioned that they too have signed the Texecom NDA and would help if they could. Surely there must be a way round this seeming impasse?

As far as I am concerned, Texecom have sold a whole load more Ricochet devices to me than I would ever have needed for just an alarm system! Texecom has replaced many of my Aqara, Yolink, Sonoff etc. detectors and even mains switches.

**Comment by lodesmets** [comment]
> I wish I could open source it fully but I've signed an NDA with Texecom who won't allow it.

Hey, I saw another python integration. And he said this:
I have spoken to the team who approve the NDA’s and they have stated that you are able to release your program but you cannot disclose details of the protocol documentation.
https://github.com/davidMbrooke/texecom-connect


But thanks for the response. I will try to update the mqtt broker
